### ISSUE TITLE
Question: Should WordPress links remain inside cP?

### ISSUE THREAD

**Issue by stefanos82** [calmPress/calmpress#151]
As I already have asked [this question](https://github.com/ClassicPress/ClassicPress-v1/issues/204) to ClassicPress, it seems it's applicable to calmPress as well.

I used silver searcher `ag` and have found lots of files that contain WordPress links in them.

Are you going to change those files to point at calmPress or are you going to keep them as is for now?

**Comment by markkap** [comment]
was mostly done in ClassicPress/ClassicPress-v1#219. There are probably some more links but that was a very boring thing to do and I gave up when I felt that the state is good enough for now.

Didn't touch anything out of `src` because still need to think if the unit tests and the .pot maker are worth to be maintained as part of calmPress at all.

It is also debatable if there is any point in duplicating content like how to create a page template or a child theme in calmPress.org as at least for some time it is going to be the same.

**Comment by stefanos82** [comment]
The lighter it gets the better. Keep it up! :+1:
